import twitter from "../assets/twitter.png";
import facebook from "../assets/Facebook_logo.png";
import AddJob from "./pages/business/AddJob";

const jobs = [
  {
    id: 1,
    title: "Senior Software Engineer",
    company: "Microsoft",
    companyLogo: facebook,
    location: "Istanbul",
    workstyle: "Hybrid",
    type: "Full-time",
    industry: "Technology",
    experience: "5+ years",
    rating: 4.7,
    applicants: 210,
    isVerified: true,
    overview:
      "Microsoft is looking for a skilled Senior Software Engineer to develop scalable cloud applications for enterprise clients.",
    responsibilities: [
      "Design and implement cloud-based solutions using Azure services.",
      "Write clean, efficient, and maintainable code in C# and .NET.",
      "Collaborate with cross-functional teams to define software architecture.",
      "Optimize application performance and scalability.",
      "Mentor junior engineers and conduct technical reviews.",
    ],
    about:
      "Microsoft is a global leader in software, services, devices, and solutions that help individuals and businesses realize their full potential.",
  },
  {
    id: 2,
    title: "Digital Marketing Specialist",
    company: "Nike",
    companyLogo: twitter,
    location: "Istanbul",
    workstyle: "Remote",
    type: "Full-time",
    industry: "Retail",
    experience: "3-5 years",
    rating: 4.5,
    applicants: 150,
    isVerified: true,
    overview:
      "Nike is searching for an experienced Digital Marketing Specialist to enhance our brand presence online and drive digital campaigns.",
    responsibilities: [
      "Develop and execute digital marketing campaigns across multiple platforms.",
      "Analyze key performance metrics and optimize ad spend.",
      "Collaborate with content and design teams to create engaging content.",
      "Manage social media accounts and influencer partnerships.",
      "Monitor market trends and consumer behavior.",
    ],
    about:
      "Nike, Inc. is a multinational corporation that designs, develops, manufactures, and markets footwear, apparel, equipment, and accessories.",
  },
  {
    id: 3,
    title: "Financial Analyst",
    company: "Garanti BBVA",
    companyLogo: twitter,
    location: "Ankara",
    workstyle: "On-site",
    type: "Full-time",
    industry: "Finance",
    experience: "1-3 years",
    rating: 4.6,
    applicants: 98,
    isVerified: true,
    overview:
      "Garanti BBVA is hiring a Financial Analyst to assess financial statements and market trends for investment strategies.",
    responsibilities: [
      "Analyze financial data to support investment decisions.",
      "Prepare reports on financial performance and risks.",
      "Collaborate with portfolio managers to optimize strategies.",
      "Assist in budget planning and forecasting.",
      "Evaluate economic trends and competitor performance.",
    ],
    about:
      "Garanti BBVA is one of Turkey's leading private banks, providing a wide range of financial services to its customers.",
  },
  {
    id: 4,
    title: "Human Resources Manager",
    company: "Turkish Airlines",
    companyLogo: facebook,
    location: "Istanbul",
    workstyle: "Hybrid",
    type: "Full-time",
    industry: "Aviation",
    experience: "5+ years",
    rating: 4.3,
    applicants: 85,
    isVerified: true,
    overview:
      "Turkish Airlines seeks an experienced HR Manager to lead recruitment, employee relations, and performance management initiatives.",
    responsibilities: [
      "Develop and implement HR policies and procedures.",
      "Manage talent acquisition and employee retention programs.",
      "Handle employee relations and conflict resolution.",
      "Oversee performance management and training programs.",
      "Ensure compliance with labor laws and regulations.",
    ],
    about:
      "Turkish Airlines is the national flag carrier airline of Turkey, providing service to numerous destinations worldwide.",
  },
  {
    id: 5,
    title: "Cybersecurity Specialist",
    company: "ASELSAN",
    companyLogo: twitter,
    location: "Ankara",
    workstyle: "On-site",
    type: "Full-time",
    industry: "Defense",
    experience: "3-5 years",
    rating: 4.8,
    applicants: 65,
    isVerified: true,
    overview:
      "ASELSAN is looking for a Cybersecurity Specialist to enhance security measures and protect critical infrastructure.",
    responsibilities: [
      "Monitor and analyze security threats and vulnerabilities.",
      "Implement security policies and best practices.",
      "Conduct penetration testing and risk assessments.",
      "Ensure compliance with cybersecurity regulations.",
      "Investigate security breaches and develop countermeasures.",
    ],
    about:
      "ASELSAN is a leading defense electronics company in Turkey, specializing in military and civilian communication systems.",
  },
  {
    id: 6,
    title: "Sales Executive",
    company: "Coca-Cola Türkiye",
    companyLogo: "cocacola.png",
    location: "Izmir",
    workstyle: "Hybrid",
    type: "Full-time",
    industry: "FMCG",
    experience: "1-3 years",
    rating: 4.2,
    applicants: 120,
    isVerified: true,
    overview:
      "Coca-Cola Türkiye is hiring a Sales Executive to drive market growth and expand client relationships in the beverage sector.",
    responsibilities: [
      "Identify and develop new sales opportunities.",
      "Build and maintain relationships with key customers.",
      "Analyze market trends and competitor strategies.",
      "Achieve sales targets and revenue growth.",
      "Collaborate with marketing and product teams.",
    ],
    about:
      "Coca-Cola Türkiye is a subsidiary of The Coca-Cola Company, one of the world's largest beverage companies.",
  },
  {
    id: 7,
    title: "Operations Manager",
    company: "Getir",
    companyLogo: "getir.png",
    location: "Istanbul",
    workstyle: "On-site",
    type: "Full-time",
    industry: "E-commerce",
    experience: "5+ years",
    rating: 4.4,
    applicants: 140,
    isVerified: true,
    overview:
      "Getir is looking for an Operations Manager to optimize delivery processes and improve logistics efficiency.",
    responsibilities: [
      "Oversee daily operations and ensure efficiency.",
      "Optimize supply chain and delivery logistics.",
      "Monitor key performance indicators and take action.",
      "Lead a team of operational staff.",
      "Identify areas for cost reduction and process improvement.",
    ],
    about:
      "Getir is a Turkish on-demand delivery service that allows users to order groceries and essentials via a mobile app.",
  },
  {
    id: 8,
    title: "UX Designer",
    company: "Trendyol",
    companyLogo: "trendyol.png",
    location: "Istanbul",
    workstyle: "Hybrid",
    type: "Full-time",
    industry: "E-commerce",
    experience: "3-5 years",
    rating: 4.5,
    applicants: 180,
    isVerified: true,
    overview:
      "Trendyol is hiring a UX Designer to create engaging and user-friendly shopping experiences.",
    responsibilities: [
      "Design user interfaces for web and mobile applications.",
      "Conduct user research and usability testing.",
      "Develop wireframes and prototypes.",
      "Collaborate with developers and product teams.",
      "Ensure brand consistency in UI elements.",
    ],
    about:
      "Trendyol is one of Turkey's leading e-commerce platforms, offering a wide range of products and services.",
  },
  {
    id: 9,
    title: "Machine Learning Engineer",
    company: "Huawei Türkiye",
    companyLogo: "huawei.png",
    location: "Ankara",
    workstyle: "Remote",
    type: "Full-time",
    industry: "Technology",
    experience: "3-5 years",
    rating: 4.6,
    applicants: 90,
    isVerified: true,
    overview:
      "Huawei Türkiye is hiring a Machine Learning Engineer to develop AI solutions for smart devices and telecom networks.",
    responsibilities: [
      "Build and optimize machine learning models.",
      "Process large datasets for AI applications.",
      "Deploy models in cloud-based environments.",
      "Work with cross-functional teams to implement AI solutions.",
      "Monitor and improve model performance.",
    ],
    about:
      "Huawei is a global leader in ICT infrastructure and smart devices, committed to building a fully connected, intelligent world.",
  },
  {
    id: 10,
    title: "Biomedical Engineer",
    company: "Siemens Healthineers Türkiye",
    companyLogo: "siemens.png",
    location: "Istanbul",
    workstyle: "On-site",
    type: "Full-time",
    industry: "Healthcare",
    experience: "1-3 years",
    rating: 4.3,
    applicants: 75,
    isVerified: true,
    overview:
      "Siemens Healthineers Türkiye is hiring a Biomedical Engineer to work on innovative medical technologies.",
    responsibilities: [
      "Design and test medical devices and equipment.",
      "Ensure compliance with healthcare regulations.",
      "Collaborate with medical professionals and researchers.",
      "Analyze biomedical data for improved patient care.",
      "Maintain and troubleshoot medical equipment.",
    ],
    about:
      "Siemens Healthineers is a leading global medical technology company, dedicated to transforming healthcare.",
  },

  {
    id: 11,
    title: "Software Engineer",
    company: "Google Türkiye",
    companyLogo: "google.png",
    location: "Istanbul",
    workstyle: "Hybrid",
    type: "Full-time",
    industry: "Technology",
    experience: "3-5 years",
    rating: 4.8,
    applicants: 190,
    isVerified: true,
    overview:
      "Google Türkiye is seeking a Software Engineer to develop scalable backend services for cloud applications.",
    responsibilities: [
      "Develop and maintain scalable backend systems.",
      "Write efficient, reusable, and reliable Python/Go code.",
      "Optimize database performance and security.",
      "Collaborate with frontend and AI teams on new features.",
      "Ensure application security and cloud infrastructure stability.",
    ],
  },
  {
    id: 12,
    title: "Software Engineer",
    company: "Amazon Türkiye",
    companyLogo: "amazon.png",
    location: "Ankara",
    workstyle: "Remote",
    type: "Full-time",
    industry: "Technology",
    experience: "3-5 years",
    rating: 4.6,
    applicants: 155,
    isVerified: true,
    overview:
      "Amazon Türkiye is hiring a Software Engineer to develop AI-powered recommendation systems.",
    responsibilities: [
      "Develop and optimize AI-driven recommendation algorithms.",
      "Work with data scientists to enhance machine learning models.",
      "Implement scalable and high-performance APIs.",
      "Ensure compliance with data privacy regulations.",
      "Debug and maintain cloud-based applications.",
    ],
  },
  {
    id: 13,
    title: "HR Specialist",
    company: "LC Waikiki",
    companyLogo: "lcwaikiki.png",
    location: "Istanbul",
    workstyle: "On-site",
    type: "Full-time",
    industry: "Retail",
    experience: "1-3 years",
    rating: 4.2,
    applicants: 95,
    isVerified: true,
    overview:
      "LC Waikiki is looking for an HR Specialist to handle recruitment and employee engagement.",
    responsibilities: [
      "Manage end-to-end recruitment processes.",
      "Support onboarding and training programs.",
      "Ensure compliance with labor laws and company policies.",
      "Handle employee relations and grievance procedures.",
      "Assist with performance appraisal and workforce planning.",
    ],
  },
  {
    id: 14,
    title: "HR Specialist",
    company: "Borusan Holding",
    companyLogo: "borusan.png",
    location: "Bursa",
    workstyle: "Hybrid",
    type: "Full-time",
    industry: "Manufacturing",
    experience: "3-5 years",
    rating: 4.4,
    applicants: 78,
    isVerified: true,
    overview:
      "Borusan Holding is hiring an HR Specialist to oversee talent acquisition and performance management.",
    responsibilities: [
      "Develop recruitment strategies for technical and managerial roles.",
      "Coordinate performance management and evaluation programs.",
      "Support training and leadership development initiatives.",
      "Manage HR analytics and reporting for decision-making.",
      "Ensure compliance with employment and workplace laws.",
    ],
  },
  {
    id: 15,
    title: "Marketing Manager",
    company: "Vestel",
    companyLogo: "vestel.png",
    location: "Manisa",
    workstyle: "On-site",
    type: "Full-time",
    industry: "Electronics",
    experience: "5+ years",
    rating: 4.3,
    applicants: 135,
    isVerified: true,
    overview:
      "Vestel is hiring a Marketing Manager to oversee brand strategy and digital marketing efforts.",
    responsibilities: [
      "Develop and execute global marketing campaigns.",
      "Analyze market trends and consumer behavior.",
      "Lead content creation and social media marketing strategies.",
      "Manage relationships with advertising agencies.",
      "Ensure brand consistency across all platforms.",
    ],
  },
  {
    id: 16,
    title: "Marketing Manager",
    company: "Turkcell",
    companyLogo: "turkcell.png",
    location: "Istanbul",
    workstyle: "Hybrid",
    type: "Full-time",
    industry: "Telecommunications",
    experience: "3-5 years",
    rating: 4.5,
    applicants: 175,
    isVerified: true,
    overview:
      "Turkcell is looking for a Marketing Manager to lead customer engagement strategies.",
    responsibilities: [
      "Design and implement targeted customer engagement campaigns.",
      "Optimize marketing spend for maximum ROI.",
      "Develop partnerships with influencers and media companies.",
      "Monitor digital marketing KPIs and campaign performance.",
      "Enhance brand positioning and awareness.",
    ],
  },
  {
    id: 17,
    title: "Financial Analyst",
    company: "Akbank",
    companyLogo: "akbank.png",
    location: "Istanbul",
    workstyle: "On-site",
    type: "Full-time",
    industry: "Finance",
    experience: "3-5 years",
    rating: 4.7,
    applicants: 200,
    isVerified: true,
    overview:
      "Akbank is seeking a Financial Analyst to analyze investments and forecast financial trends.",
    responsibilities: [
      "Evaluate financial statements and business risks.",
      "Conduct industry research and competitor analysis.",
      "Assist in developing investment portfolios.",
      "Prepare reports for senior management.",
      "Support financial decision-making with in-depth analysis.",
    ],
  },
  {
    id: 18,
    title: "Business Consultant",
    company: "PwC Türkiye",
    companyLogo: "pwc.png",
    location: "Ankara",
    workstyle: "Hybrid",
    type: "Full-time",
    industry: "Consulting",
    experience: "3-5 years",
    rating: 4.6,
    applicants: 85,
    isVerified: true,
    overview:
      "PwC Türkiye is hiring a Business Consultant to provide advisory services for corporate clients.",
    responsibilities: [
      "Develop strategic solutions for business growth.",
      "Conduct market research and data analysis.",
      "Work closely with clients on process optimization.",
      "Prepare presentations and reports for stakeholders.",
      "Assist in risk assessment and compliance evaluations.",
    ],
  },
  {
    id: 19,
    title: "Operations Manager",
    company: "MNG Kargo",
    companyLogo: "mng.png",
    location: "Istanbul",
    workstyle: "On-site",
    type: "Full-time",
    industry: "Logistics",
    experience: "5+ years",
    rating: 4.2,
    applicants: 160,
    isVerified: true,
    overview:
      "MNG Kargo is looking for an Operations Manager to oversee warehouse and delivery logistics.",
    responsibilities: [
      "Optimize supply chain and distribution processes.",
      "Ensure timely and cost-effective deliveries.",
      "Monitor warehouse efficiency and stock management.",
      "Lead operational teams to meet performance targets.",
      "Develop strategies for process improvement.",
    ],
  },
  {
    id: 20,
    title: "UX Designer",
    company: "Hepsiburada",
    companyLogo: "hepsiburada.png",
    location: "Istanbul",
    workstyle: "Hybrid",
    type: "Full-time",
    industry: "E-commerce",
    experience: "3-5 years",
    rating: 4.5,
    applicants: 140,
    isVerified: true,
    overview:
      "Hepsiburada is hiring a UX Designer to create seamless e-commerce experiences.",
    responsibilities: [
      "Design user-friendly interfaces for desktop and mobile.",
      "Conduct usability testing and user research.",
      "Develop wireframes and interactive prototypes.",
      "Work with developers to implement UI/UX improvements.",
      "Analyze user behavior and iterate on design.",
    ],
  },

  {
    id: 21,
    title: "Frontend Developer",
    company: "Trendyol",
    companyLogo: "trendyol.png",
    location: "Istanbul",
    workstyle: "Hybrid",
    type: "Full-time",
    industry: "E-commerce",
    experience: "3-5 years",
    rating: 4.6,
    applicants: 185,
    isVerified: true,
    overview:
      "Trendyol is hiring a Frontend Developer to create intuitive and responsive UI experiences for millions of users.",
    responsibilities: [
      "Develop and optimize frontend applications using React and TypeScript.",
      "Ensure UI components are responsive and accessible.",
      "Collaborate with backend teams for seamless API integration.",
      "Maintain and improve existing design systems.",
      "Optimize website performance and loading speeds.",
    ],
  },
  {
    id: 22,
    title: "Frontend Developer",
    company: "Hepsiburada",
    companyLogo: "hepsiburada.png",
    location: "Ankara",
    workstyle: "Remote",
    type: "Full-time",
    industry: "E-commerce",
    experience: "3-5 years",
    rating: 4.5,
    applicants: 120,
    isVerified: true,
    overview:
      "Hepsiburada is looking for a Frontend Developer to enhance customer experience on our platform.",
    responsibilities: [
      "Develop interactive and visually appealing UI components.",
      "Work closely with UX designers to implement pixel-perfect designs.",
      "Optimize frontend performance and handle state management.",
      "Ensure cross-browser compatibility and mobile responsiveness.",
      "Participate in Agile development and sprint planning.",
    ],
  },
  {
    id: 23,
    title: "Customer Support Specialist",
    company: "Getir",
    companyLogo: "getir.png",
    location: "Izmir",
    workstyle: "On-site",
    type: "Full-time",
    industry: "E-commerce",
    experience: "1-3 years",
    rating: 4.3,
    applicants: 140,
    isVerified: true,
    overview:
      "Getir is looking for a Customer Support Specialist to ensure top-notch service for our customers.",
    responsibilities: [
      "Handle customer inquiries and complaints professionally.",
      "Provide troubleshooting support via phone, chat, and email.",
      "Collaborate with logistics and operations teams to resolve issues.",
      "Ensure high customer satisfaction and quick response times.",
      "Maintain records of customer interactions and feedback.",
    ],
  },
  {
    id: 24,
    title: "Customer Support Specialist",
    company: "Turkish Airlines",
    companyLogo: "thy.png",
    location: "Antalya",
    workstyle: "On-site",
    type: "Full-time",
    industry: "Aviation",
    experience: "0-1 years",
    rating: 4.4,
    applicants: 100,
    isVerified: true,
    overview:
      "Turkish Airlines is looking for a Customer Support Specialist to assist passengers with flight-related inquiries.",
    responsibilities: [
      "Assist customers with ticket bookings and flight changes.",
      "Handle baggage claim and lost item reports.",
      "Provide accurate flight and travel information.",
      "Resolve customer issues quickly and efficiently.",
      "Ensure compliance with aviation industry regulations.",
    ],
  },
  {
    id: 25,
    title: "Data Scientist",
    company: "Huawei Türkiye",
    companyLogo: "huawei.png",
    location: "Istanbul",
    workstyle: "Hybrid",
    type: "Full-time",
    industry: "Technology",
    experience: "3-5 years",
    rating: 4.7,
    applicants: 175,
    isVerified: true,
    overview:
      "Huawei Türkiye is hiring a Data Scientist to develop AI-powered analytics solutions.",
    responsibilities: [
      "Analyze large datasets to extract meaningful insights.",
      "Develop machine learning models for predictive analytics.",
      "Optimize algorithms for efficiency and scalability.",
      "Collaborate with engineers to integrate AI models into production.",
      "Present findings and insights to business stakeholders.",
    ],
  },
  {
    id: 26,
    title: "Data Scientist",
    company: "Turkcell",
    companyLogo: "turkcell.png",
    location: "Ankara",
    workstyle: "Remote",
    type: "Full-time",
    industry: "Telecommunications",
    experience: "3-5 years",
    rating: 4.5,
    applicants: 145,
    isVerified: true,
    overview:
      "Turkcell is looking for a Data Scientist to analyze network performance and user behavior.",
    responsibilities: [
      "Develop predictive models to optimize network efficiency.",
      "Analyze customer data to improve user experience.",
      "Work with big data technologies like Spark and Hadoop.",
      "Create dashboards and reports for data-driven decision-making.",
      "Collaborate with business units to implement AI solutions.",
    ],
  },
  {
    id: 27,
    title: "Legal Advisor",
    company: "Borusan Holding",
    companyLogo: "borusan.png",
    location: "Bursa",
    workstyle: "On-site",
    type: "Full-time",
    industry: "Manufacturing",
    experience: "5+ years",
    rating: 4.6,
    applicants: 80,
    isVerified: true,
    overview:
      "Borusan Holding is hiring a Legal Advisor to manage corporate legal affairs and compliance.",
    responsibilities: [
      "Draft and review legal contracts and agreements.",
      "Ensure compliance with Turkish business regulations.",
      "Advise management on corporate legal strategies.",
      "Handle dispute resolution and litigation matters.",
      "Monitor changes in labor and business laws.",
    ],
  },
  {
    id: 28,
    title: "Legal Advisor",
    company: "Garanti BBVA",
    companyLogo: "garanti.png",
    location: "Istanbul",
    workstyle: "Hybrid",
    type: "Full-time",
    industry: "Finance",
    experience: "5+ years",
    rating: 4.5,
    applicants: 95,
    isVerified: true,
    overview:
      "Garanti BBVA is looking for a Legal Advisor to oversee financial compliance and corporate governance.",
    responsibilities: [
      "Ensure compliance with banking and financial regulations.",
      "Review contracts, agreements, and corporate policies.",
      "Provide legal advice on mergers and acquisitions.",
      "Handle regulatory reporting and risk assessments.",
      "Liaise with external legal advisors and regulators.",
    ],
  },
  {
    id: 29,
    title: "Operations Manager",
    company: "Arçelik",
    companyLogo: "arcelik.png",
    location: "Izmir",
    workstyle: "On-site",
    type: "Full-time",
    industry: "Electronics",
    experience: "5+ years",
    rating: 4.3,
    applicants: 135,
    isVerified: true,
    overview:
      "Arçelik is hiring an Operations Manager to optimize manufacturing and logistics.",
    responsibilities: [
      "Monitor and improve production efficiency.",
      "Oversee supply chain and warehouse operations.",
      "Ensure compliance with safety and environmental regulations.",
      "Implement process improvements for cost reduction.",
      "Lead and train operational teams.",
    ],
  },
  {
    id: 30,
    title: "Biomedical Engineer",
    company: "Medtronic Türkiye",
    companyLogo: "medtronic.png",
    location: "Istanbul",
    workstyle: "On-site",
    type: "Full-time",
    industry: "Healthcare",
    experience: "1-3 years",
    rating: 4.4,
    applicants: 105,
    isVerified: true,
    overview:
      "Medtronic Türkiye is hiring a Biomedical Engineer to develop and maintain medical devices.",
    responsibilities: [
      "Design and test biomedical equipment.",
      "Ensure compliance with healthcare standards and regulations.",
      "Work with hospitals and clinics for product support.",
      "Conduct research on medical device improvements.",
      "Assist in the development of innovative medical technologies.",
    ],
  },

  {
    id: 31,
    title: "Senior Product Designer",
    company: "Twitter",
    companyLogo: twitter,
    location: "Berlin",
    workstyle: "Remote",
    type: "Full-time",
    industry: "Technology",
    experience: "5+ years",
    rating: 4.3,
    applicants: 123,
    isVerified: true,
    overview:
      "Twitter is looking for a Senior Product Designer to join our growing design team in Berlin. In this role, you'll be responsible for leading the design of key features that millions of people use daily. You'll work closely with product managers, engineers, and researchers to create intuitive and impactful user experiences that shape the future of public conversation.",
    responsibilities: [
      "Lead the end-to-end design process for major product initiatives",
      "Create user flows, wireframes, and high-fidelity prototypes",
      "Conduct and participate in design critiques to ensure high-quality solutions",
      "Mentor junior designers and contribute to our design system",
      "Collaborate with research teams to gather and incorporate user feedback",
      "Present design solutions to senior stakeholders and executive team",
      "Partner with engineering to ensure pixel-perfect implementation",
      "Contribute to strategic product decisions and roadmap planning",
    ],
    about:
      "Twitter is where the world comes to share ideas and stay informed. Our purpose is to serve the public conversation – it's essential to connecting the world. We're committed to protecting the health of the public conversation while respecting fundamental human rights. Our team of passionate individuals works together to create products that have real-world impact.  Twitter is where the world comes to sha  Twitter is where the world comes to sha  Twitter is where the world comes to sha  Twitter is where the world comes to sha  Twitter is where the world comes to sha Twitter is where the world comes to sha Twitter is where the world comes to sha Twitter is where the world comes to sha Twitter is where the world comes to sha Twitter is where the world comes to sha Twitter is where the world comes to shaJoin us in building the future of public discourse.",
  },
  {
    id: 32,
    title: "Senior Software Engineer, Frontend",
    company: "Facebook",
    companyLogo: facebook,
    location: "Menlo Park",
    workstyle: "Hybrid",
    type: "Full-time",
    industry: "Technology",
    experience: "5+ years",
    rating: 4.6,
    applicants: 305,
    isVerified: true,
    overview:
      "Meta is seeking an experienced Frontend Engineer to join our News Feed team. You'll be working on features that billions of people use every day, building high-performance user interfaces and contributing to our next-generation web application framework. This is an opportunity to shape the future of how people connect and share online.",
    responsibilities: [
      "Architect and implement complex frontend features using React and modern JavaScript",
      "Optimize application performance and ensure cross-browser compatibility",
      "Write clean, maintainable code with comprehensive test coverage",
      "Collaborate with designers to implement pixel-perfect, responsive interfaces",
      "Mentor junior engineers and conduct code reviews",
      "Contribute to technical design discussions and architecture decisions",
      "Work with product managers to define technical requirements",
      "Participate in our engineering on-call rotation",
      "Drive best practices and technical innovations across the team",
    ],
    about:
      "Meta builds technologies that help people connect, find communities, and grow businesses. When Facebook launched in 2004, it changed the way people connect. Apps like Messenger, Instagram and WhatsApp further empowered billions around the world. Now, Meta is moving beyond 2D screens toward immersive experiences like augmented and virtual reality to help build the next evolution in social technology.",
  },
  {
    id: 33,
    title: "QA Automation Engineer",
    company: "Instagram",
    companyLogo: twitter,
    location: "San Francisco",
    workstyle: "On-site",
    type: "Contract",
    industry: "Technology",
    experience: "3-5 years",
    rating: 4.1,
    applicants: 186,
    isVerified: true,
    overview:
      "Instagram is looking for a QA Automation Engineer to join our Stories team. You'll be responsible for building and maintaining our automated testing framework, ensuring the quality and reliability of our features that reach millions of users. This role combines technical expertise with a keen eye for user experience.",
    responsibilities: [
      "Develop and maintain automated test suites using Python and JavaScript",
      "Design and implement test frameworks for web and mobile applications",
      "Create comprehensive test plans and test cases for new features",
      "Perform exploratory testing and identify potential issues",
      "Work with developers to debug and resolve product issues",
      "Monitor and analyze test results to identify patterns and areas for improvement",
      "Implement performance testing and monitoring solutions",
      "Document testing procedures and maintain test documentation",
      "Collaborate with cross-functional teams to ensure quality standards",
    ],
    about:
      "Instagram is the world's leading photo-sharing platform, home to more than a billion users worldwide. Our mission is to bring you closer to the people and things you love. We're committed to fostering a positive, diverse, and safe community where people can express themselves freely and creatively.",
  },
  {
    id: 34,
    title: "Junior UI/UX Designer",
    company: "Kadir Has University",
    companyLogo: facebook,
    location: "Istanbul",
    workstyle: "On-site",
    type: "Internship",
    industry: "Education",
    experience: "0-1 years",
    rating: 4.2,
    applicants: 51,
    isVerified: true,
    overview:
      "Kadir Has University is seeking a talented Junior UI/UX Designer to join our digital transformation team. This role offers an excellent opportunity for someone starting their design career to work on meaningful projects that impact thousands of students and faculty members. You'll be involved in redesigning our digital platforms and creating new tools for education.",
    responsibilities: [
      "Create user-centered designs for web and mobile applications",
      "Develop wireframes and prototypes for new features and improvements",
      "Conduct user research and usability testing",
      "Create and maintain design documentation and style guides",
      "Collaborate with developers to ensure design feasibility",
      "Participate in design sprints and brainstorming sessions",
      "Help maintain consistency across all university digital platforms",
      "Gather and analyze user feedback to improve designs",
    ],
    about:
      "Kadir Has University is one of Turkey's leading private universities, committed to providing world-class education and research opportunities. Founded in 1997, we have grown to become a center of academic excellence, combining traditional educational values with innovative approaches to learning and technology. Our campus in the heart of Istanbul serves as a hub for intellectual and cultural exchange.",
  },
  {
    id: 35,
    title: "Junior UI/UX Designer",
    company: "Kadir Has University",
    companyLogo: facebook,
    location: "Istanbul",
    workstyle: "On-site",
    type: "Internship",
    industry: "Education",
    experience: "0-1 years",
    rating: 4.2,
    applicants: 51,
    isVerified: true,
    overview:
      "Kadir Has University is seeking a talented Junior UI/UX Designer to join our digital transformation team. This role offers an excellent opportunity for someone starting their design career to work on meaningful projects that impact thousands of students and faculty members. You'll be involved in redesigning our digital platforms and creating new tools for education.",
    responsibilities: [
      "Create user-centered designs for web and mobile applications",
      "Develop wireframes and prototypes for new features and improvements",
      "Conduct user research and usability testing",
      "Create and maintain design documentation and style guides",
      "Collaborate with developers to ensure design feasibility",
      "Participate in design sprints and brainstorming sessions",
      "Help maintain consistency across all university digital platforms",
      "Gather and analyze user feedback to improve designs",
    ],
    about:
      "Kadir Has University is one of Turkey's leading private universities, committed to providing world-class education and research opportunities. Founded in 1997, we have grown to become a center of academic excellence, combining traditional educational values with innovative approaches to learning and technology. Our campus in the heart of Istanbul serves as a hub for intellectual and cultural exchange.",
  },
  {
    id: 36,
    title: "Junior UI/UX Designer",
    company: "Kadir Has University",
    companyLogo: facebook,
    location: "Istanbul",
    workstyle: "On-site",
    type: "Internship",
    industry: "Education",
    experience: "0-1 years",
    rating: 4.2,
    applicants: 51,
    isVerified: true,
    overview:
      "Kadir Has University is seeking a talented Junior UI/UX Designer to join our digital transformation team. This role offers an excellent opportunity for someone starting their design career to work on meaningful projects that impact thousands of students and faculty members. You'll be involved in redesigning our digital platforms and creating new tools for education.",
    responsibilities: [
      "Create user-centered designs for web and mobile applications",
      "Develop wireframes and prototypes for new features and improvements",
      "Conduct user research and usability testing",
      "Create and maintain design documentation and style guides",
      "Collaborate with developers to ensure design feasibility",
      "Participate in design sprints and brainstorming sessions",
      "Help maintain consistency across all university digital platforms",
      "Gather and analyze user feedback to improve designs",
    ],
    about:
      "Kadir Has University is one of Turkey's leading private universities, committed to providing world-class education and research opportunities. Founded in 1997, we have grown to become a center of academic excellence, combining traditional educational values with innovative approaches to learning and technology. Our campus in the heart of Istanbul serves as a hub for intellectual and cultural exchange.",
  },
];

export default jobs;
